/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.BorrowAndReturnGallons;

import Controllers.BorrowAndReturnGallonsController;
import Forms.FrameFormModal;
import Forms.ReturnGallons;
import Forms.ReturnGallonsModal;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author CALUAG FAMILY
 */
public class BorrowAndReturnGallons extends javax.swing.JPanel {

    /**
     * Creates new form BorrowAndReturnGallons
     */
    BorrowAndReturnGallonsController borrowandreturnControol = new BorrowAndReturnGallonsController();
    JPanel lalagyanan;
    
            
    public BorrowAndReturnGallons(JPanel lalagyanan) {
        initComponents();
        this.lalagyanan = lalagyanan;
        InitRun();
        borrowgallontbl.getTableHeader().setFont(new Font("MS Gothic",Font.BOLD,15));
        Color theadcolor = Color.decode("#90E0EF");
        borrowgallontbl.getTableHeader().setBackground(theadcolor);
        borrowgallontbl.getTableHeader().setPreferredSize(new Dimension(100, 40));
        
        returngallontable.getTableHeader().setFont(new Font("MS Gothic",Font.BOLD,15));
        
        
    }
    
     private void InitRun(){
        borrowandreturnControol.showBorrowGallon(borrowgallontbl);
         borrowandreturnControol.showReturnGallon(returngallontable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        returngallontable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addBtn1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        borrowgallontbl = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 180, 216));
        setPreferredSize(new java.awt.Dimension(1000, 620));

        returngallontable.setAutoCreateRowSorter(true);
        returngallontable.setFont(new java.awt.Font("MS Gothic", 0, 15)); // NOI18N
        returngallontable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Customer_Id	", "Gallon_Id", "Gallon_Quantity", "Date_Return"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        returngallontable.setGridColor(new java.awt.Color(102, 102, 102));
        returngallontable.setRowHeight(25);
        returngallontable.setShowGrid(true);
        returngallontable.setShowHorizontalLines(false);
        returngallontable.setShowVerticalLines(false);
        returngallontable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returngallontableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(returngallontable);
        if (returngallontable.getColumnModel().getColumnCount() > 0) {
            returngallontable.getColumnModel().getColumn(0).setMinWidth(50);
            returngallontable.getColumnModel().getColumn(0).setPreferredWidth(50);
            returngallontable.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel2.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Manage Return Gallons");

        addBtn.setBackground(new java.awt.Color(0, 180, 216));
        addBtn.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        addBtn.setText("+");
        addBtn.setBorderPainted(false);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBtn)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(addBtn)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        jLabel3.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Manage Borrow Gallons");

        addBtn1.setBackground(new java.awt.Color(0, 180, 216));
        addBtn1.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        addBtn1.setText("+");
        addBtn1.setBorderPainted(false);
        addBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBtn1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        borrowgallontbl.setAutoCreateRowSorter(true);
        borrowgallontbl.setFont(new java.awt.Font("MS Gothic", 0, 15)); // NOI18N
        borrowgallontbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Customer Name", "Gallon Type", "Gallon Quantity", "Date Borrowed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        borrowgallontbl.setGridColor(new java.awt.Color(102, 102, 102));
        borrowgallontbl.setRowHeight(25);
        borrowgallontbl.setShowGrid(true);
        borrowgallontbl.setShowHorizontalLines(false);
        borrowgallontbl.setShowVerticalLines(false);
        borrowgallontbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrowgallontblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(borrowgallontbl);
        if (borrowgallontbl.getColumnModel().getColumnCount() > 0) {
            borrowgallontbl.getColumnModel().getColumn(0).setMinWidth(40);
            borrowgallontbl.getColumnModel().getColumn(0).setPreferredWidth(40);
            borrowgallontbl.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void returngallontableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returngallontableMouseClicked
        int id = (int) returngallontable.getValueAt(returngallontable.getSelectedRow(),0);
        new FrameFormModal(12,id,returngallontable,lalagyanan).setVisible(true);
    }//GEN-LAST:event_returngallontableMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        new FrameFormModal(12,0,returngallontable,lalagyanan).setVisible(true);
    }//GEN-LAST:event_addBtnActionPerformed

    private void addBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn1ActionPerformed
        // TODO add your handling code here:
        new FrameFormModal(14,0,borrowgallontbl,lalagyanan).setVisible(true);
    }//GEN-LAST:event_addBtn1ActionPerformed

    private void borrowgallontblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowgallontblMouseClicked
        int id = (int) borrowgallontbl.getValueAt(borrowgallontbl.getSelectedRow(),0);
        new ReturnGallons(id,lalagyanan,returngallontable,borrowgallontbl).setVisible(true);
    }//GEN-LAST:event_borrowgallontblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addBtn1;
    private javax.swing.JTable borrowgallontbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable returngallontable;
    // End of variables declaration//GEN-END:variables
}
