/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.ButtonsController;
import javax.swing.JPanel;

/**
 *
 * @author Kevin Felix Caluag
 */
public class DeveloperAndAdminButtons extends javax.swing.JPanel {

    /**
     * Creates new form DeveloperAndAdminButtons
     */
    
    ButtonsController buttonControll;
    JPanel lalagyanan;
    
    public DeveloperAndAdminButtons(JPanel lalagyanan) {
        initComponents();
        buttonControll = new ButtonsController(lalagyanan);
        buttonControll.DashboardButton(dashboard);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        hovUsers = new javax.swing.JPanel();
        users = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hovGallons = new javax.swing.JPanel();
        gallons = new javax.swing.JLabel();
        hovSales = new javax.swing.JPanel();
        sale = new javax.swing.JLabel();
        hovRefilled = new javax.swing.JPanel();
        refilled = new javax.swing.JLabel();
        hovSupplier = new javax.swing.JPanel();
        supplier = new javax.swing.JLabel();
        hovPromos = new javax.swing.JPanel();
        promos = new javax.swing.JLabel();
        hovDeliveries = new javax.swing.JPanel();
        deliveries = new javax.swing.JLabel();
        hovCustomer = new javax.swing.JPanel();
        customer = new javax.swing.JLabel();
        hovDashboard = new javax.swing.JPanel();
        dashboard = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(250, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(64, 43, 100));
        kGradientPanel1.setkStartColor(new java.awt.Color(64, 43, 100));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><center>Water Refilling <br> System </center></html>");
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 100));
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 90));

        hovUsers.setBackground(new java.awt.Color(64, 43, 100));
        hovUsers.setPreferredSize(new java.awt.Dimension(250, 50));
        hovUsers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        users.setBackground(new java.awt.Color(64, 43, 100));
        users.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        users.setForeground(new java.awt.Color(255, 255, 255));
        users.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        users.setText("Users");
        users.setIconTextGap(10);
        users.setPreferredSize(new java.awt.Dimension(250, 50));
        users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersMouseClicked(evt);
            }
        });
        hovUsers.add(users, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/56-removebg-preview.png"))); // NOI18N
        hovUsers.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, -1));

        kGradientPanel1.add(hovUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 205, 250, -1));

        hovGallons.setBackground(new java.awt.Color(64, 43, 100));
        hovGallons.setPreferredSize(new java.awt.Dimension(250, 50));

        gallons.setBackground(new java.awt.Color(85, 65, 118));
        gallons.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        gallons.setForeground(new java.awt.Color(255, 255, 255));
        gallons.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gallons.setText("Gallons");
        gallons.setIconTextGap(10);
        gallons.setPreferredSize(new java.awt.Dimension(250, 50));
        gallons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gallonsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hovGallonsLayout = new javax.swing.GroupLayout(hovGallons);
        hovGallons.setLayout(hovGallonsLayout);
        hovGallonsLayout.setHorizontalGroup(
            hovGallonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovGallonsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(gallons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256))
        );
        hovGallonsLayout.setVerticalGroup(
            hovGallonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovGallonsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(gallons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kGradientPanel1.add(hovGallons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 265, -1, -1));

        hovSales.setBackground(new java.awt.Color(64, 43, 100));
        hovSales.setPreferredSize(new java.awt.Dimension(250, 50));

        sale.setBackground(new java.awt.Color(85, 65, 118));
        sale.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        sale.setForeground(new java.awt.Color(255, 255, 255));
        sale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sale.setText("Sales");
        sale.setIconTextGap(10);
        sale.setPreferredSize(new java.awt.Dimension(250, 50));
        sale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hovSalesLayout = new javax.swing.GroupLayout(hovSales);
        hovSales.setLayout(hovSalesLayout);
        hovSalesLayout.setHorizontalGroup(
            hovSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovSalesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hovSalesLayout.setVerticalGroup(
            hovSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovSalesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kGradientPanel1.add(hovSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 325, -1, -1));

        hovRefilled.setBackground(new java.awt.Color(64, 43, 100));
        hovRefilled.setPreferredSize(new java.awt.Dimension(250, 50));

        refilled.setBackground(new java.awt.Color(85, 65, 118));
        refilled.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        refilled.setForeground(new java.awt.Color(255, 255, 255));
        refilled.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        refilled.setText("Refilled Gallons");
        refilled.setIconTextGap(10);
        refilled.setPreferredSize(new java.awt.Dimension(250, 50));
        refilled.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refilledMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hovRefilledLayout = new javax.swing.GroupLayout(hovRefilled);
        hovRefilled.setLayout(hovRefilledLayout);
        hovRefilledLayout.setHorizontalGroup(
            hovRefilledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovRefilledLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(refilled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hovRefilledLayout.setVerticalGroup(
            hovRefilledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovRefilledLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(refilled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kGradientPanel1.add(hovRefilled, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 385, -1, -1));

        hovSupplier.setBackground(new java.awt.Color(64, 43, 100));
        hovSupplier.setPreferredSize(new java.awt.Dimension(250, 50));

        supplier.setBackground(new java.awt.Color(85, 65, 118));
        supplier.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        supplier.setForeground(new java.awt.Color(255, 255, 255));
        supplier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        supplier.setText("Supplier");
        supplier.setIconTextGap(10);
        supplier.setPreferredSize(new java.awt.Dimension(250, 50));
        supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hovSupplierLayout = new javax.swing.GroupLayout(hovSupplier);
        hovSupplier.setLayout(hovSupplierLayout);
        hovSupplierLayout.setHorizontalGroup(
            hovSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovSupplierLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hovSupplierLayout.setVerticalGroup(
            hovSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovSupplierLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kGradientPanel1.add(hovSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 445, -1, -1));

        hovPromos.setBackground(new java.awt.Color(64, 43, 100));
        hovPromos.setPreferredSize(new java.awt.Dimension(250, 50));

        promos.setBackground(new java.awt.Color(85, 65, 118));
        promos.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        promos.setForeground(new java.awt.Color(255, 255, 255));
        promos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        promos.setText("Promos");
        promos.setIconTextGap(10);
        promos.setPreferredSize(new java.awt.Dimension(250, 50));
        promos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                promosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hovPromosLayout = new javax.swing.GroupLayout(hovPromos);
        hovPromos.setLayout(hovPromosLayout);
        hovPromosLayout.setHorizontalGroup(
            hovPromosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovPromosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(promos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hovPromosLayout.setVerticalGroup(
            hovPromosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovPromosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(promos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kGradientPanel1.add(hovPromos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 505, -1, -1));

        hovDeliveries.setBackground(new java.awt.Color(64, 43, 100));
        hovDeliveries.setPreferredSize(new java.awt.Dimension(250, 50));

        deliveries.setBackground(new java.awt.Color(85, 65, 118));
        deliveries.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        deliveries.setForeground(new java.awt.Color(255, 255, 255));
        deliveries.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deliveries.setText("Deliveries");
        deliveries.setIconTextGap(10);
        deliveries.setPreferredSize(new java.awt.Dimension(250, 50));
        deliveries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deliveriesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hovDeliveriesLayout = new javax.swing.GroupLayout(hovDeliveries);
        hovDeliveries.setLayout(hovDeliveriesLayout);
        hovDeliveriesLayout.setHorizontalGroup(
            hovDeliveriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovDeliveriesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(deliveries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hovDeliveriesLayout.setVerticalGroup(
            hovDeliveriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovDeliveriesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(deliveries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kGradientPanel1.add(hovDeliveries, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 625, -1, -1));

        hovCustomer.setBackground(new java.awt.Color(64, 43, 100));
        hovCustomer.setPreferredSize(new java.awt.Dimension(250, 50));

        customer.setBackground(new java.awt.Color(85, 65, 118));
        customer.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        customer.setForeground(new java.awt.Color(255, 255, 255));
        customer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customer.setText("Customer");
        customer.setIconTextGap(10);
        customer.setPreferredSize(new java.awt.Dimension(250, 50));
        customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hovCustomerLayout = new javax.swing.GroupLayout(hovCustomer);
        hovCustomer.setLayout(hovCustomerLayout);
        hovCustomerLayout.setHorizontalGroup(
            hovCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovCustomerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hovCustomerLayout.setVerticalGroup(
            hovCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovCustomerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kGradientPanel1.add(hovCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 565, -1, -1));

        hovDashboard.setBackground(new java.awt.Color(85, 65, 118));
        hovDashboard.setPreferredSize(new java.awt.Dimension(250, 50));

        dashboard.setBackground(new java.awt.Color(85, 65, 118));
        dashboard.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboard.setText("Dashboard");
        dashboard.setIconTextGap(10);
        dashboard.setPreferredSize(new java.awt.Dimension(250, 50));
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icons/ss-removebg-preview-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout hovDashboardLayout = new javax.swing.GroupLayout(hovDashboard);
        hovDashboard.setLayout(hovDashboardLayout);
        hovDashboardLayout.setHorizontalGroup(
            hovDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hovDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
            .addGroup(hovDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hovDashboardLayout.setVerticalGroup(
            hovDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hovDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(hovDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(dashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kGradientPanel1.add(hovDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, 50));
        kGradientPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 210, 10));

        add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        buttonControll.DashboardButton(dashboard);
        buttonControll.setC(hovDashboard);
        buttonControll.resetC(hovUsers);
        buttonControll.resetC(hovGallons);
        buttonControll.resetC(hovSales);
        buttonControll.resetC(hovRefilled);
        buttonControll.resetC(hovSupplier);
        buttonControll.resetC(hovPromos);
        buttonControll.resetC(hovDeliveries);
        buttonControll.resetC(hovCustomer);
    }//GEN-LAST:event_dashboardMouseClicked

    private void usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseClicked
        buttonControll.UsersButton(users);
        buttonControll.setC(hovUsers);
        buttonControll.resetC(hovDashboard);
        buttonControll.resetC(hovGallons);
        buttonControll.resetC(hovSales);
        buttonControll.resetC(hovRefilled);
        buttonControll.resetC(hovSupplier);
        buttonControll.resetC(hovPromos);
        buttonControll.resetC(hovDeliveries);
        buttonControll.resetC(hovCustomer);
    }//GEN-LAST:event_usersMouseClicked

    private void gallonsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gallonsMouseClicked
        buttonControll.GallonsButton(gallons);
        buttonControll.setC(hovGallons);
        buttonControll.resetC(hovDashboard);
        buttonControll.resetC(hovUsers);
        buttonControll.resetC(hovSales);
        buttonControll.resetC(hovRefilled);
        buttonControll.resetC(hovSupplier);
        buttonControll.resetC(hovPromos);
        buttonControll.resetC(hovDeliveries);
        buttonControll.resetC(hovCustomer);
    }//GEN-LAST:event_gallonsMouseClicked

    private void saleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleMouseClicked
       buttonControll.SalesButton(sale);
       buttonControll.setC(hovSales);
        buttonControll.resetC(hovDashboard);
        buttonControll.resetC(hovUsers);
        buttonControll.resetC(hovGallons);
        buttonControll.resetC(hovRefilled);
        buttonControll.resetC(hovSupplier);
        buttonControll.resetC(hovPromos);
        buttonControll.resetC(hovDeliveries);
        buttonControll.resetC(hovCustomer);
    }//GEN-LAST:event_saleMouseClicked

    private void refilledMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refilledMouseClicked
        buttonControll.RefilledGallonsButton(refilled);
        buttonControll.setC(hovRefilled);
        buttonControll.resetC(hovDashboard);
        buttonControll.resetC(hovUsers);
        buttonControll.resetC(hovGallons);
        buttonControll.resetC(hovSales);
        buttonControll.resetC(hovSupplier);
        buttonControll.resetC(hovPromos);
        buttonControll.resetC(hovDeliveries);
        buttonControll.resetC(hovCustomer);
    }//GEN-LAST:event_refilledMouseClicked

    private void supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseClicked
       buttonControll.SupplierButton(supplier);
       buttonControll.setC(hovSupplier);
        buttonControll.resetC(hovDashboard);
        buttonControll.resetC(hovUsers);
        buttonControll.resetC(hovGallons);
        buttonControll.resetC(hovSales);
        buttonControll.resetC(hovRefilled);
        buttonControll.resetC(hovPromos);
        buttonControll.resetC(hovDeliveries);
        buttonControll.resetC(hovCustomer);
    }//GEN-LAST:event_supplierMouseClicked

    private void promosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_promosMouseClicked
        buttonControll.PromosButton(promos);
        buttonControll.setC(hovPromos);
        buttonControll.resetC(hovDashboard);
        buttonControll.resetC(hovUsers);
        buttonControll.resetC(hovGallons);
        buttonControll.resetC(hovSales);
        buttonControll.resetC(hovRefilled);
        buttonControll.resetC(hovSupplier);
        buttonControll.resetC(hovDeliveries);
        buttonControll.resetC(hovCustomer);
    }//GEN-LAST:event_promosMouseClicked

    private void deliveriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveriesMouseClicked
        buttonControll.DeliveriesButton(deliveries);
        buttonControll.setC(hovDeliveries);
        buttonControll.resetC(hovDashboard);
        buttonControll.resetC(hovUsers);
        buttonControll.resetC(hovGallons);
        buttonControll.resetC(hovSales);
        buttonControll.resetC(hovRefilled);
        buttonControll.resetC(hovSupplier);
        buttonControll.resetC(hovPromos);
        buttonControll.resetC(hovCustomer);
    }//GEN-LAST:event_deliveriesMouseClicked

    private void customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerMouseClicked
        buttonControll.CustomerButton(customer);
        buttonControll.setC(hovCustomer);
        buttonControll.resetC(hovDashboard);
        buttonControll.resetC(hovUsers);
        buttonControll.resetC(hovGallons);
        buttonControll.resetC(hovSales);
        buttonControll.resetC(hovPromos);
        buttonControll.resetC(hovRefilled);
        buttonControll.resetC(hovSupplier);
        buttonControll.resetC(hovDeliveries);
    }//GEN-LAST:event_customerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customer;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel deliveries;
    private javax.swing.JLabel gallons;
    private javax.swing.JPanel hovCustomer;
    private javax.swing.JPanel hovDashboard;
    private javax.swing.JPanel hovDeliveries;
    private javax.swing.JPanel hovGallons;
    private javax.swing.JPanel hovPromos;
    private javax.swing.JPanel hovRefilled;
    private javax.swing.JPanel hovSales;
    private javax.swing.JPanel hovSupplier;
    private javax.swing.JPanel hovUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel promos;
    private javax.swing.JLabel refilled;
    private javax.swing.JLabel sale;
    private javax.swing.JLabel supplier;
    private javax.swing.JLabel users;
    // End of variables declaration//GEN-END:variables
}
