/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.ButtonsController;
import javax.swing.JPanel;

/**
 *
 * @author Kevin Felix Caluag
 */
public class DeveloperAndAdminButtons extends javax.swing.JPanel {

    /**
     * Creates new form DeveloperAndAdminButtons
     */
    
    ButtonsController buttonControll;
    JPanel lalagyanan;
    
    public DeveloperAndAdminButtons(JPanel lalagyanan) {
        initComponents();
        buttonControll = new ButtonsController(lalagyanan);
        buttonControll.DashboardButton(dashboard);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        hovDashboard = new javax.swing.JPanel();
        dashboard = new javax.swing.JLabel();
        hovUsers = new javax.swing.JPanel();
        users = new javax.swing.JLabel();
        hovGallons = new javax.swing.JPanel();
        gallons = new javax.swing.JLabel();
        hovSales = new javax.swing.JPanel();
        sale = new javax.swing.JLabel();
        hovRefilled = new javax.swing.JPanel();
        refilled = new javax.swing.JLabel();
        hovSupplier = new javax.swing.JPanel();
        supplier = new javax.swing.JLabel();
        hovPromos = new javax.swing.JPanel();
        promos = new javax.swing.JLabel();
        hovDeliveries = new javax.swing.JPanel();
        deliveries = new javax.swing.JLabel();
        hovCustomer = new javax.swing.JPanel();
        customer = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 204, 255));
        setPreferredSize(new java.awt.Dimension(250, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>DEVELOPER AND ADMINISTRATOR <br> <center>BUTTONS</center></html>");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 2, 1, new java.awt.Color(0, 0, 255)));
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 100));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 100));

        hovDashboard.setBackground(new java.awt.Color(83, 140, 198));
        hovDashboard.setPreferredSize(new java.awt.Dimension(250, 50));

        dashboard.setBackground(new java.awt.Color(51, 51, 255));
        dashboard.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboard.setText("Dashboard");
        dashboard.setIconTextGap(10);
        dashboard.setPreferredSize(new java.awt.Dimension(250, 50));
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hovDashboardLayout = new javax.swing.GroupLayout(hovDashboard);
        hovDashboard.setLayout(hovDashboardLayout);
        hovDashboardLayout.setHorizontalGroup(
            hovDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        hovDashboardLayout.setVerticalGroup(
            hovDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(hovDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 50));

        hovUsers.setBackground(new java.awt.Color(83, 140, 198));
        hovUsers.setPreferredSize(new java.awt.Dimension(250, 50));

        users.setBackground(new java.awt.Color(51, 51, 255));
        users.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        users.setForeground(new java.awt.Color(255, 255, 255));
        users.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        users.setText("Users");
        users.setIconTextGap(10);
        users.setPreferredSize(new java.awt.Dimension(250, 50));
        users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usersMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hovUsersLayout = new javax.swing.GroupLayout(hovUsers);
        hovUsers.setLayout(hovUsersLayout);
        hovUsersLayout.setHorizontalGroup(
            hovUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovUsersLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(users, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hovUsersLayout.setVerticalGroup(
            hovUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovUsersLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(users, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(hovUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 50));

        hovGallons.setBackground(new java.awt.Color(83, 140, 198));
        hovGallons.setPreferredSize(new java.awt.Dimension(250, 50));

        gallons.setBackground(new java.awt.Color(51, 51, 255));
        gallons.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        gallons.setForeground(new java.awt.Color(255, 255, 255));
        gallons.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gallons.setText("Gallons");
        gallons.setIconTextGap(10);
        gallons.setPreferredSize(new java.awt.Dimension(250, 50));
        gallons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gallonsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gallonsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gallonsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hovGallonsLayout = new javax.swing.GroupLayout(hovGallons);
        hovGallons.setLayout(hovGallonsLayout);
        hovGallonsLayout.setHorizontalGroup(
            hovGallonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovGallonsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(gallons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hovGallonsLayout.setVerticalGroup(
            hovGallonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovGallonsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(gallons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(hovGallons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 250, -1));

        hovSales.setBackground(new java.awt.Color(83, 140, 198));
        hovSales.setPreferredSize(new java.awt.Dimension(250, 50));

        sale.setBackground(new java.awt.Color(51, 51, 255));
        sale.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        sale.setForeground(new java.awt.Color(255, 255, 255));
        sale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sale.setText("Sales");
        sale.setIconTextGap(10);
        sale.setPreferredSize(new java.awt.Dimension(250, 50));
        sale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saleMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hovSalesLayout = new javax.swing.GroupLayout(hovSales);
        hovSales.setLayout(hovSalesLayout);
        hovSalesLayout.setHorizontalGroup(
            hovSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovSalesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hovSalesLayout.setVerticalGroup(
            hovSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovSalesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(hovSales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, -1));

        hovRefilled.setBackground(new java.awt.Color(83, 140, 198));
        hovRefilled.setPreferredSize(new java.awt.Dimension(250, 50));

        refilled.setBackground(new java.awt.Color(51, 51, 255));
        refilled.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        refilled.setForeground(new java.awt.Color(255, 255, 255));
        refilled.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        refilled.setText("Refilled Gallons");
        refilled.setIconTextGap(10);
        refilled.setPreferredSize(new java.awt.Dimension(250, 50));
        refilled.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refilledMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refilledMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refilledMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hovRefilledLayout = new javax.swing.GroupLayout(hovRefilled);
        hovRefilled.setLayout(hovRefilledLayout);
        hovRefilledLayout.setHorizontalGroup(
            hovRefilledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovRefilledLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(refilled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hovRefilledLayout.setVerticalGroup(
            hovRefilledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovRefilledLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(refilled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(hovRefilled, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 250, -1));

        hovSupplier.setBackground(new java.awt.Color(83, 140, 198));
        hovSupplier.setPreferredSize(new java.awt.Dimension(250, 50));

        supplier.setBackground(new java.awt.Color(51, 51, 255));
        supplier.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        supplier.setForeground(new java.awt.Color(255, 255, 255));
        supplier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        supplier.setText("Supplier");
        supplier.setIconTextGap(10);
        supplier.setPreferredSize(new java.awt.Dimension(250, 50));
        supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplierMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hovSupplierLayout = new javax.swing.GroupLayout(hovSupplier);
        hovSupplier.setLayout(hovSupplierLayout);
        hovSupplierLayout.setHorizontalGroup(
            hovSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovSupplierLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hovSupplierLayout.setVerticalGroup(
            hovSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovSupplierLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(hovSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 250, -1));

        hovPromos.setBackground(new java.awt.Color(83, 140, 198));
        hovPromos.setPreferredSize(new java.awt.Dimension(250, 50));

        promos.setBackground(new java.awt.Color(51, 51, 255));
        promos.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        promos.setForeground(new java.awt.Color(255, 255, 255));
        promos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        promos.setText("Promos");
        promos.setIconTextGap(10);
        promos.setPreferredSize(new java.awt.Dimension(250, 50));
        promos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                promosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                promosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                promosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hovPromosLayout = new javax.swing.GroupLayout(hovPromos);
        hovPromos.setLayout(hovPromosLayout);
        hovPromosLayout.setHorizontalGroup(
            hovPromosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovPromosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(promos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hovPromosLayout.setVerticalGroup(
            hovPromosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovPromosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(promos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(hovPromos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 250, -1));

        hovDeliveries.setBackground(new java.awt.Color(83, 140, 198));
        hovDeliveries.setPreferredSize(new java.awt.Dimension(250, 50));

        deliveries.setBackground(new java.awt.Color(51, 51, 255));
        deliveries.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        deliveries.setForeground(new java.awt.Color(255, 255, 255));
        deliveries.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deliveries.setText("Deliveries");
        deliveries.setIconTextGap(10);
        deliveries.setPreferredSize(new java.awt.Dimension(250, 50));
        deliveries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deliveriesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deliveriesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deliveriesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hovDeliveriesLayout = new javax.swing.GroupLayout(hovDeliveries);
        hovDeliveries.setLayout(hovDeliveriesLayout);
        hovDeliveriesLayout.setHorizontalGroup(
            hovDeliveriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovDeliveriesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(deliveries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hovDeliveriesLayout.setVerticalGroup(
            hovDeliveriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovDeliveriesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(deliveries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(hovDeliveries, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 250, -1));

        hovCustomer.setBackground(new java.awt.Color(83, 140, 198));
        hovCustomer.setPreferredSize(new java.awt.Dimension(250, 50));

        customer.setBackground(new java.awt.Color(51, 51, 255));
        customer.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        customer.setForeground(new java.awt.Color(255, 255, 255));
        customer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customer.setText("Customer");
        customer.setIconTextGap(10);
        customer.setPreferredSize(new java.awt.Dimension(250, 50));
        customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customerMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hovCustomerLayout = new javax.swing.GroupLayout(hovCustomer);
        hovCustomer.setLayout(hovCustomerLayout);
        hovCustomerLayout.setHorizontalGroup(
            hovCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovCustomerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hovCustomerLayout.setVerticalGroup(
            hovCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hovCustomerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(hovCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 250, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        buttonControll.DashboardButton(dashboard);
    }//GEN-LAST:event_dashboardMouseClicked

    private void dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseEntered
        buttonControll.setC(hovDashboard);
    }//GEN-LAST:event_dashboardMouseEntered

    private void dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseExited
        buttonControll.resetC(hovDashboard);
    }//GEN-LAST:event_dashboardMouseExited

    private void usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseClicked
        buttonControll.UsersButton(users);
    }//GEN-LAST:event_usersMouseClicked

    private void usersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseEntered
        buttonControll.setC(hovUsers);
    }//GEN-LAST:event_usersMouseEntered

    private void usersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseExited
        buttonControll.resetC(hovUsers);
    }//GEN-LAST:event_usersMouseExited

    private void gallonsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gallonsMouseClicked
        buttonControll.GallonsButton(gallons);
    }//GEN-LAST:event_gallonsMouseClicked

    private void gallonsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gallonsMouseEntered
        buttonControll.setC(hovGallons);
    }//GEN-LAST:event_gallonsMouseEntered

    private void gallonsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gallonsMouseExited
        buttonControll.resetC(hovGallons);
    }//GEN-LAST:event_gallonsMouseExited

    private void saleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleMouseClicked
       buttonControll.SalesButton(sale);
    }//GEN-LAST:event_saleMouseClicked

    private void saleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleMouseEntered
        buttonControll.setC(hovSales);
    }//GEN-LAST:event_saleMouseEntered

    private void saleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleMouseExited
        buttonControll.resetC(hovSales);
    }//GEN-LAST:event_saleMouseExited

    private void refilledMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refilledMouseClicked
        buttonControll.RefilledGallonsButton(refilled);
    }//GEN-LAST:event_refilledMouseClicked

    private void refilledMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refilledMouseEntered
       buttonControll.setC(hovRefilled);
    }//GEN-LAST:event_refilledMouseEntered

    private void refilledMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refilledMouseExited
         buttonControll.resetC(hovRefilled);
    }//GEN-LAST:event_refilledMouseExited

    private void supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseClicked
       buttonControll.SupplierButton(supplier);
    }//GEN-LAST:event_supplierMouseClicked

    private void supplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseEntered
        buttonControll.setC(hovSupplier);
    }//GEN-LAST:event_supplierMouseEntered

    private void supplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseExited
        buttonControll.resetC(hovSupplier);
    }//GEN-LAST:event_supplierMouseExited

    private void promosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_promosMouseClicked
        buttonControll.PromosButton(promos);
    }//GEN-LAST:event_promosMouseClicked

    private void promosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_promosMouseEntered
        buttonControll.setC(hovPromos);
    }//GEN-LAST:event_promosMouseEntered

    private void promosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_promosMouseExited
        buttonControll.resetC(hovPromos);
    }//GEN-LAST:event_promosMouseExited

    private void deliveriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveriesMouseClicked
        buttonControll.DeliveriesButton(deliveries);
    }//GEN-LAST:event_deliveriesMouseClicked

    private void deliveriesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveriesMouseEntered
        buttonControll.setC(hovDeliveries);
    }//GEN-LAST:event_deliveriesMouseEntered

    private void deliveriesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveriesMouseExited
        buttonControll.resetC(hovDeliveries);
    }//GEN-LAST:event_deliveriesMouseExited

    private void customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerMouseClicked
        buttonControll.CustomerButton(customer);
    }//GEN-LAST:event_customerMouseClicked

    private void customerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerMouseEntered
        buttonControll.setC(hovCustomer);
    }//GEN-LAST:event_customerMouseEntered

    private void customerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerMouseExited
         buttonControll.resetC(hovCustomer);
    }//GEN-LAST:event_customerMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customer;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel deliveries;
    private javax.swing.JLabel gallons;
    private javax.swing.JPanel hovCustomer;
    private javax.swing.JPanel hovDashboard;
    private javax.swing.JPanel hovDeliveries;
    private javax.swing.JPanel hovGallons;
    private javax.swing.JPanel hovPromos;
    private javax.swing.JPanel hovRefilled;
    private javax.swing.JPanel hovSales;
    private javax.swing.JPanel hovSupplier;
    private javax.swing.JPanel hovUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel promos;
    private javax.swing.JLabel refilled;
    private javax.swing.JLabel sale;
    private javax.swing.JLabel supplier;
    private javax.swing.JLabel users;
    // End of variables declaration//GEN-END:variables
}
