/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author ChelseaTorres
 */
public class Transactions extends javax.swing.JPanel {

    /**
     * Creates new form Transactions
     */
    public Transactions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        walkedIn = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        deliveries = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("TRANSACTION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 190, 100));

        walkedIn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(walkedIn);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 160, 1080, -1));

        jLabel2.setText("Walked In");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 150, 40));

        deliveries.setText("Deliveries");
        deliveries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deliveriesMouseClicked(evt);
            }
        });
        add(deliveries, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 130, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void deliveriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveriesMouseClicked
       
    }//GEN-LAST:event_deliveriesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deliveries;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable walkedIn;
    // End of variables declaration//GEN-END:variables
}
