/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.CustomerController;
import Controllers.GallonsController;
import Controllers.PromosController;
import Controllers.TransactionController;
import Controllers.UsersController;
import Models.SupplierModel;
import Models.TransactionsModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KevinCaluag
 */
public class Transaction extends javax.swing.JPanel {

    /**
     * Creates new form Transaction
     */
    CustomerController customerControll = new CustomerController();
    PromosController promoControll = new PromosController();
    UsersController userControll = new UsersController();
    TransactionController transactionControll = new TransactionController();
    GallonsController gallonsControll = new GallonsController();
    
    JPanel lalagyanan;
    
    public Transaction(JPanel lalagyanan) {
        initComponents();
        this.lalagyanan = lalagyanan;
        transactionControll.fetchComboBoxValue(Customer_Id, Promo_Id, User_Id,gallonType_Id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        isborrowgallons = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Customer_Id = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        gallonType_Id = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        serviceOffered = new javax.swing.JComboBox<>();
        Promo_Id = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        User_Id = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        notborrowgallon = new javax.swing.JRadioButton();
        isborrowgallon = new javax.swing.JRadioButton();
        addToCartBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        DateToBeDeliver = new com.toedter.calendar.JDateChooser();
        DateOrder = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        gallonQuantity = new javax.swing.JSpinner();
        payBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(990, 480));

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Customer Fullname", "Gallon Type", "Gallon Quantity", "Promo", "Borrowed Gallon", "Service", "Date Order", "Date To Deliver"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cartTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cartTable);
        if (cartTable.getColumnModel().getColumnCount() > 0) {
            cartTable.getColumnModel().getColumn(0).setMinWidth(40);
            cartTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            cartTable.getColumnModel().getColumn(0).setMaxWidth(40);
            cartTable.getColumnModel().getColumn(1).setPreferredWidth(120);
            cartTable.getColumnModel().getColumn(5).setMinWidth(45);
            cartTable.getColumnModel().getColumn(5).setPreferredWidth(45);
            cartTable.getColumnModel().getColumn(5).setMaxWidth(45);
            cartTable.getColumnModel().getColumn(8).setResizable(false);
        }

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.add(Customer_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 160, 30));

        jLabel3.setText("Customer Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, 30));

        jPanel2.add(gallonType_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 160, 30));

        jLabel4.setText("Gallon Type");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, 30));

        jLabel5.setText("Service Option");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 80, 30));

        serviceOffered.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Walk IN", "Pick Up", "Deliver" }));
        jPanel2.add(serviceOffered, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 160, 30));

        jPanel2.add(Promo_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 160, 30));

        jLabel6.setText("Date To Be Deliver");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 100, 30));

        jLabel7.setText("Is Borrowed Gallon");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 110, 30));

        jPanel2.add(User_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 160, 30));

        jLabel8.setText("Assisted By");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 80, 30));

        isborrowgallons.add(notborrowgallon);
        notborrowgallon.setText("no");
        jPanel2.add(notborrowgallon, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        isborrowgallons.add(isborrowgallon);
        isborrowgallon.setText("yes");
        jPanel2.add(isborrowgallon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        addToCartBtn.setText("ADD");
        addToCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartBtnActionPerformed(evt);
            }
        });
        jPanel2.add(addToCartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 240, 40));

        jLabel9.setText("Quantity");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 80, 30));

        jLabel10.setText("Date Order");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, 30));
        jPanel2.add(DateToBeDeliver, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 160, 30));

        DateOrder.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DateOrderPropertyChange(evt);
            }
        });
        jPanel2.add(DateOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 160, 30));

        jLabel11.setText("Promo");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 30));
        jPanel2.add(gallonQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 160, 30));

        payBtn.setText("Pay");
        payBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBtnActionPerformed(evt);
            }
        });
        jPanel2.add(payBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 240, 40));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

     String strDates;
     String strDates1;
     
    private void addToCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartBtnActionPerformed
        //            String name = customerControll.customerlist().get(Customer_Id.getS).getFullname().
        DateFormat dateFormat = new SimpleDateFormat("MMM-dd-yyy");  
        strDates = dateFormat.format(DateOrder.getDate());
        strDates1 = dateFormat.format(DateToBeDeliver.getDate());
        String isborrow="";
        if(isborrowgallon.isSelected()){
            isborrow = "Yes";
        }if(notborrowgallon.isSelected()){
            isborrow = "No";
        }
        Object[] row = { cartTable.getRowCount()+1,Customer_Id.getSelectedItem() ,gallonType_Id.getSelectedItem(), gallonQuantity.getValue() ,Promo_Id.getSelectedItem() , isborrow , serviceOffered.getSelectedItem(),strDates,strDates1};
        
        String code, code1, rw0, rw1, custname, msf=null;
          int x;
          for(x = 0; x<cartTable.getRowCount();x++){
            code = gallonType_Id.getSelectedItem().toString();
            custname = Customer_Id.getSelectedItem().toString();
            code1 = serviceOffered.getSelectedItem().toString();
            rw0 = String.valueOf(cartTable.getValueAt(x, 2));
            rw1 = String.valueOf(cartTable.getValueAt(x, 6));
            if (code.equals(rw0) && code1.equals(rw1) && custname.equals(cartTable.getValueAt(x, 1).toString())){
                msf = String.valueOf(x);
                break;
            }
          }
          
          if (msf != null){
            int quant = Integer.parseInt(cartTable.getValueAt(x,3).toString());
            cartTable.setValueAt(Integer.parseInt(gallonQuantity.getValue().toString()) + quant, x, 3);
          }else{
              transactionControll.addToCart(cartTable, row);
          }
    }//GEN-LAST:event_addToCartBtnActionPerformed

    
    private void trylang(){
        DefaultTableModel model = (DefaultTableModel)cartTable.getModel();

          String code1,code2,code3, rw0,DDorDR,DDorDP, msf=null;
          int custid=0;
          int servicetype=0;
          int promoid=0;
          int status=0;
          String gallonid = "";
          int x;
            for(x = 0; x<cartTable.getRowCount();x++){
                for(int i=0;i<=Customer_Id.getItemCount();i++){
                if (cartTable.getValueAt(x, 1).toString().equals(Customer_Id.getItemAt(i))) {
                    try {
                        custid = customerControll.customerlist().get(i).getID();
                    } catch (SQLException ex) {
                        Logger.getLogger(Transaction.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
                
                for(int k=0; k<=gallonType_Id.getItemCount();k++){
                    if (cartTable.getValueAt(x, 2).toString().equals(gallonType_Id.getItemAt(k))) {
                        try {
                            gallonid = gallonsControll.gallonList().get(k).getCode();
                        } catch (SQLException ex) {
                            Logger.getLogger(Transaction.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
                
                for(int k=0; k<=Promo_Id.getItemCount();k++){
                    if (cartTable.getValueAt(x, 4).toString().equals(Promo_Id.getItemAt(k))) {
                        try {
                            promoid = promoControll.promosList().get(k).getId();
                        } catch (SQLException ex) {
                            Logger.getLogger(Transaction.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
                
                for(int k=0; k<=serviceOffered.getItemCount();k++){
                    if (cartTable.getValueAt(x, 6).toString().equals(serviceOffered.getItemAt(k))) {
                            servicetype = k;   
                    }
                }
                
                transactionControll.supplierList(custid, cartTable.getValueAt(x,7).toString(), cartTable.getValueAt(x,8).toString(), gallonid, Integer.parseInt(cartTable.getValueAt(x,3).toString()), promoid, servicetype, 0, 1);         
        }
            
//            Object[] rows = { cartTable.getRowCount()+1,Customer_Id.getSelectedItem() ,gallonType_Id.getSelectedItem(), gallonQuantity.getValue() ,Promo_Id.getSelectedItem() , isborrow , serviceOffered.getSelectedItem(),strDates,strDates1};
//            `Customer_Id`, `DOorDR`, `DDorDP`, `Gallon_Id`, `Quantity`, `Promo_Id`, `ServiceType`, `Status`, `User_Id`
            
        
    }
    
    private void DateOrderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DateOrderPropertyChange
        setMinimumDate();
    }//GEN-LAST:event_DateOrderPropertyChange

    private void payBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBtnActionPerformed
        trylang();
    }//GEN-LAST:event_payBtnActionPerformed

    private void cartTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartTableMouseClicked
        transactionControll.deleteDataFromCart(cartTable.getSelectedRow(), cartTable);
    }//GEN-LAST:event_cartTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        transactionControll.addDeliveries(cartTable);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void setMinimumDate(){
        DateToBeDeliver.setMinSelectableDate(DateOrder.getDate());
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Customer_Id;
    private com.toedter.calendar.JDateChooser DateOrder;
    private com.toedter.calendar.JDateChooser DateToBeDeliver;
    private javax.swing.JComboBox<String> Promo_Id;
    private javax.swing.JComboBox<String> User_Id;
    private javax.swing.JButton addToCartBtn;
    private javax.swing.JTable cartTable;
    private javax.swing.JSpinner gallonQuantity;
    private javax.swing.JComboBox<String> gallonType_Id;
    private javax.swing.JRadioButton isborrowgallon;
    private javax.swing.ButtonGroup isborrowgallons;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton notborrowgallon;
    private javax.swing.JButton payBtn;
    private javax.swing.JComboBox<String> serviceOffered;
    // End of variables declaration//GEN-END:variables
}
