/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Controllers.ContainerController;
import Controllers.CustomerController;
import Controllers.DeliveriesController;
import Controllers.PromosController;
import Controllers.UserController;
import Models.DeliveriesModel;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author KevinCaluag
 */
public class DeliveriesModal extends javax.swing.JPanel {

    /**
     * Creates new form DeliveriesModal
     */
    static int btn_id;
    DeliveriesModel deliveriesModel;
    DeliveriesController deliveriesControll = new DeliveriesController();
    CustomerController customerControll = new CustomerController();
    PromosController promoControll = new PromosController();
    UserController userControll = new UserController();
    
    static JTable promoTable;
    static JPanel lalagyanan;
    static JFrame out;
    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
    
    public DeliveriesModal(JFrame out,int btn_id,JTable promoTable,JPanel lalagyanan) {
        this.btn_id = btn_id;
        this.promoTable = promoTable;
        this.lalagyanan = lalagyanan;
        this.out = out;
        initComponents();
        checkBtn(btn_id);
    }
    private void checkBtn(int btn_id){
        if (btn_id==0) {   
            deliveriesControll.fetchComboBoxValue(Customer_Id, Promo_Id, User_Id);
            Date_Delivered.setDate(deliveriesControll.getDateNow());
            updatebtn.setVisible(false);
            deletebtn.setVisible(false);
        }else{
            deliveriesControll.fetchComboBoxValue(Customer_Id, Promo_Id, User_Id);
            deliveriesControll.getDeliveriesInfo(btn_id, Customer_Id, Date_Delivered, Quantity, Promo_Id, Status, User_Id);
            addbtn.setVisible(false);
            updatebtn.setVisible(true);
            deletebtn.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Customer_Id = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Date_Delivered = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        Quantity = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        Promo_Id = new javax.swing.JComboBox<>();
        lbls = new javax.swing.JLabel();
        Status = new javax.swing.JComboBox<>();
        lbls1 = new javax.swing.JLabel();
        User_Id = new javax.swing.JComboBox<>();
        updatebtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(64, 43, 100));
        setPreferredSize(new java.awt.Dimension(310, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Customer_Id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Customer_IdMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Customer_IdMousePressed(evt);
            }
        });
        Customer_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_IdActionPerformed(evt);
            }
        });
        add(Customer_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 180, 40));

        jLabel2.setText("Quantity");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 80, 40));

        jLabel3.setText("Customer Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, 40));
        add(Date_Delivered, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 180, 40));

        jLabel4.setText("Date Delivered");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 40));
        add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 90, 40));

        jLabel5.setText("Promo");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 80, 40));

        add(Promo_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 180, 40));

        lbls.setText("Status");
        add(lbls, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 80, 40));

        Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Delivered" }));
        add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 180, 40));

        lbls1.setText("Delivered By");
        add(lbls1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 80, 40));

        add(User_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 180, 40));

        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 110, 43));

        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 110, 43));

        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 110, 43));
    }// </editor-fold>//GEN-END:initComponents

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        try {
            deliveriesModel = new DeliveriesModel(btn_id,customerControll.customerlist().get(Customer_Id.getSelectedIndex()).getId(),dateFormat.format(Date_Delivered.getDate()), (int) Quantity.getValue(),promoControll.promosList().get(Promo_Id.getSelectedIndex()).getId(),Status.getSelectedIndex(),userControll.userList().get(User_Id.getSelectedIndex()).getId());
            if (deliveriesControll.updateDeliveries(deliveriesModel, promoTable)) {
                out.dispose();
                new ContainerController(lalagyanan,new Views.Deliveries(lalagyanan));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DeliveriesModal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        try {
            deliveriesModel = new DeliveriesModel(btn_id,customerControll.customerlist().get(Customer_Id.getSelectedIndex()).getId(),dateFormat.format(Date_Delivered.getDate()), (int) Quantity.getValue(),promoControll.promosList().get(Promo_Id.getSelectedIndex()).getId(),Status.getSelectedIndex(),userControll.userList().get(User_Id.getSelectedIndex()).getId());
            if (deliveriesControll.addDeliveries(deliveriesModel, promoTable)) {
                out.dispose();
                new ContainerController(lalagyanan,new Views.Deliveries(lalagyanan));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DeliveriesModal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        if (deliveriesControll.deleteUser(btn_id, promoTable)) {
            out.dispose();
            new ContainerController(lalagyanan,new Views.Deliveries(lalagyanan));
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void Customer_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_IdActionPerformed
//        JOptionPane.showMessageDialog(null,"ge");
    }//GEN-LAST:event_Customer_IdActionPerformed

    private void Customer_IdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Customer_IdMouseClicked

    }//GEN-LAST:event_Customer_IdMouseClicked

    private void Customer_IdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Customer_IdMousePressed

    }//GEN-LAST:event_Customer_IdMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Customer_Id;
    private com.toedter.calendar.JDateChooser Date_Delivered;
    private javax.swing.JComboBox<String> Promo_Id;
    private javax.swing.JSpinner Quantity;
    private javax.swing.JComboBox<String> Status;
    private javax.swing.JComboBox<String> User_Id;
    public javax.swing.JButton addbtn;
    public javax.swing.JButton deletebtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbls;
    private javax.swing.JLabel lbls1;
    public javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
