/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Controllers.ContainerController;
import Controllers.DeliveriesController;
import Controllers.PromosController;
import Models.PromosModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author KevinCaluag
 */
public class PromoFormModal extends javax.swing.JPanel {

    /**
     * Creates new form PromoFormModal
     */
    static JTable promoTable;
    static JPanel lalagyanan;
    static JFrame out;
    static int btn_id;
    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
    DeliveriesController deliveriesControll = new DeliveriesController();
    PromosController promosControll = new PromosController();
    PromosModel promosModel;
    
    public PromoFormModal(JFrame out,int btn_id,JTable promoTable,JPanel lalagyanan) {
        this.btn_id = btn_id;
        this.promoTable = promoTable;
        this.lalagyanan = lalagyanan;
        this.out = out;
        initComponents();
        checkBtn(btn_id);
    }
    private void checkBtn(int btn_id){
        if (btn_id==0) {
            Date_Started.setDate(deliveriesControll.getDateNow());
            updatebtn.setVisible(false);
            deletebtn.setVisible(false);
        }else{
            promosControll.getPromosInfo(btn_id, Name, Description, Date_Started, Date_End);
            addbtn.setVisible(false);
            updatebtn.setVisible(true);
            deletebtn.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Description = new javax.swing.JTextArea();
        Date_Started = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Date_End = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 143, 81, 30));
        add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 143, 196, 30));

        jLabel2.setText("Date Started");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 81, 30));

        Description.setColumns(20);
        Description.setLineWrap(true);
        Description.setRows(5);
        Description.setTabSize(5);
        jScrollPane1.setViewportView(Description);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 200, 130));
        add(Date_Started, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 200, 30));

        jLabel3.setText("Description");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 81, 30));

        jLabel4.setText("Date End");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 81, 30));
        add(Date_End, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 200, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Promos");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 240, 30));

        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 546, 100, 43));

        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 100, 43));

        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 546, 100, 43));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("X");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 40, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
      promosModel = new PromosModel(btn_id,Name.getText(),Description.getText(),dateFormat.format(Date_Started.getDate()),dateFormat.format(Date_End.getDate()));
        if(promosControll.updatePromos(promosModel, promoTable)){
            out.dispose();
            new ContainerController(lalagyanan,new Views.Promos(lalagyanan));
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        promosModel = new PromosModel(0,Name.getText(),Description.getText(),dateFormat.format(Date_Started.getDate()),dateFormat.format(Date_End.getDate()));
        if(promosControll.addPromos(promosModel, promoTable)){
            out.dispose();
            new ContainerController(lalagyanan,new Views.Promos(lalagyanan));
        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
       if(promosControll.deletePromos(btn_id, promoTable)){
            out.dispose();
            new ContainerController(lalagyanan,new Views.Promos(lalagyanan));
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        out.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_End;
    private com.toedter.calendar.JDateChooser Date_Started;
    private javax.swing.JTextArea Description;
    private javax.swing.JTextField Name;
    public javax.swing.JButton addbtn;
    public javax.swing.JButton deletebtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
