/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Controllers.ContainerController;
import Controllers.DeliveriesController;
import Controllers.PromosController;
import Models.PromosModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTable;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author KevinCaluag
 */
public class PromoFormModal extends javax.swing.JPanel {

    /**
     * Creates new form PromoFormModal
     */
    static JTable promoTable;
    static JPanel lalagyanan;
    static JFrame out;
    static int btn_id;
    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
    DeliveriesController deliveriesControll = new DeliveriesController();
    PromosController promosControll = new PromosController();
    PromosModel promosModel;
    
    public PromoFormModal(JFrame out,int btn_id,JTable promoTable,JPanel lalagyanan) {
        this.btn_id = btn_id;
        this.promoTable = promoTable;
        this.lalagyanan = lalagyanan;
        this.out = out;
        initComponents();
        checkBtn(btn_id);
    }
    private void checkBtn(int btn_id){
        if (btn_id==0) {
            Date_Started.setDate(deliveriesControll.getDateNow());
            updatebtn.setVisible(false);
            deletebtn.setVisible(false);
        }else{
            promosControll.getPromosInfo(btn_id, Name, Description, Date_Started, Date_End);
            addbtn.setVisible(false);
            updatebtn.setVisible(true);
            deletebtn.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Description = new javax.swing.JTextArea();
        Date_Started = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Date_End = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Name = new javax.swing.JTextField();

        setBackground(new java.awt.Color(85, 64, 118));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 81, 30));

        jLabel2.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date Started");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 90, 30));

        Description.setColumns(20);
        Description.setLineWrap(true);
        Description.setRows(5);
        Description.setTabSize(5);
        Description.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DescriptionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(Description);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 200, 130));
        add(Date_Started, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 200, 30));

        jLabel3.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Description");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 81, 30));

        jLabel4.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date End");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 81, 30));
        add(Date_End, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 200, 30));

        jLabel5.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Promos");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 240, 30));

        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 100, 43));

        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 100, 43));

        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 100, 43));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("X");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusable(false);
        jButton2.setNextFocusableComponent(Name);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 40, 30));

        Name.setFont(new java.awt.Font("MS Gothic", 0, 14)); // NOI18N
        Name.setAutoscrolls(false);
        Name.setBorder(new javax.swing.border.MatteBorder(null));
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameKeyTyped(evt);
            }
        });
        add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 200, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
      promosModel = new PromosModel(btn_id,Name.getText(),Description.getText(),dateFormat.format(Date_Started.getDate()),dateFormat.format(Date_End.getDate()));
        if(promosControll.updatePromos(promosModel, promoTable)){
            out.dispose();
            new ContainerController(lalagyanan,new Views.Promos.Promos(lalagyanan));
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        promosModel = new PromosModel(0,Name.getText(),Description.getText(),dateFormat.format(Date_Started.getDate()),dateFormat.format(Date_End.getDate()));
        if(promosControll.addPromos(promosModel, promoTable)){
            out.dispose();
            new ContainerController(lalagyanan,new Views.Promos.Promos(lalagyanan));
        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
       if(promosControll.deletePromos(btn_id, promoTable)){
            out.dispose();
            new ContainerController(lalagyanan,new Views.Promos.Promos(lalagyanan));
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        out.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameKeyTyped
        // TODO add your handling code here:
            char c = evt.getKeyChar();
          if (!((c >= 'a') && (c <= 'z') || (c >= 'A') && (c <= 'Z') ||
             (c == KeyEvent.VK_PERIOD) ||
             (c == KeyEvent.VK_BACK_SPACE) ||
             (c == KeyEvent.VK_DELETE))) {
               getToolkit().beep();
             evt.consume();
          }

    }//GEN-LAST:event_NameKeyTyped

    private void DescriptionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DescriptionKeyTyped
        // TODO add your handling code here:
            char c = evt.getKeyChar();
          if (!((c >= 'a') && (c <= 'z') || (c >= 'A') && (c <= 'Z') ||
             (c == KeyEvent.VK_PERIOD) ||
             (c == KeyEvent.VK_BACK_SPACE) ||
             (c == KeyEvent.VK_DELETE))) {
               getToolkit().beep();
             evt.consume();
          }

    }//GEN-LAST:event_DescriptionKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_End;
    private com.toedter.calendar.JDateChooser Date_Started;
    private javax.swing.JTextArea Description;
    private javax.swing.JTextField Name;
    public javax.swing.JButton addbtn;
    public javax.swing.JButton deletebtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
