/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Controllers.BorrowAndReturnGallonsController;
import Controllers.ContainerController;
import Controllers.SQLController;
import Models.Return_GallonsModel;
import com.toedter.calendar.JDateChooser;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KevinCaluag
 */
public class ReturnGallonsModal extends javax.swing.JFrame {

    /**
     * Creates new form ReturnGallonsModal
     */
    
    Return_GallonsModel returngallonModel;
    BorrowAndReturnGallonsController borrowandreturngallonsControll = new BorrowAndReturnGallonsController();
    DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    SQLController sql = new SQLController();
    Connection con = sql.getConnection();
    
    static int btn_id;
    static JPanel lalagyanan;
    static JTable returngallons;
    static JTable borrowgallons;
    
    public ReturnGallonsModal(int btn_id,JPanel lalagyanan,JTable returngallons,JTable borrowgallons) {
        initComponents();
        this.btn_id = btn_id;
        this.returngallons = returngallons;
        this.lalagyanan = lalagyanan;
        this.borrowgallons = borrowgallons;
        updatebtn.setVisible(false);
        getReturnGallonsInfo(btn_id,customerName,gallonType1,gallonQuantity,DateReturn);
    }

    int borrowgallonquant;
    public void getReturnGallonsInfo(int Id,JTextField Customer_Id,JTextField gallonType_Id,JTextField gallonQuantity,JDateChooser DateReturn){
        try {
            JOptionPane.showMessageDialog(null,Id);
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM `barrow_gallons`LEFT JOIN customers ON customers.ID = barrow_gallons.Customer_Id LEFT JOIN gallons ON gallons.Code = barrow_gallons.Gallon_Id where barrow_gallons.Id =  " + Id);

            if(rs.next()){
                JOptionPane.showMessageDialog(null,rs.getString("customers.Fname") + " " + rs.getString("customers.Mname") + " " + rs.getString("customers.Lname"));
                Customer_Id.setText(rs.getString("customers.Fname") + " " + rs.getString("customers.Mname") + " " + rs.getString("customers.Lname"));
                gallonType_Id.setText(rs.getString("gallons.Gallon_Type"));
                gallonQuantity.setText(String.valueOf(rs.getInt("barrow_gallons.Gallon_Quantity")));
                borrowgallonquant = rs.getInt("barrow_gallons.Gallon_Quantity");
                DateReturn.setDate(rs.getDate("Date_Borrowed"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(BorrowAndReturnGallonsController.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        DateReturn = new com.toedter.calendar.JDateChooser();
        updatebtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        label1 = new java.awt.Label();
        gallonQuantity = new javax.swing.JTextField();
        customerName = new javax.swing.JTextField();
        gallonType1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.setMinimumSize(new java.awt.Dimension(350, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jButton2.setText("X");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 50, 40));

        jLabel3.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Customer Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 30));

        jLabel4.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Gallon Type");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 90, 30));

        jLabel9.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Quantity");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 90, 30));

        jLabel10.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Date Barrowed");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 100, 30));

        DateReturn.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DateReturnPropertyChange(evt);
            }
        });
        jPanel1.add(DateReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 190, 30));

        updatebtn.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        updatebtn.setText("UPDATE");
        updatebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 153, 255), null, null));
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        jPanel1.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 190, 30));

        addbtn.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        addbtn.setText("ADD");
        addbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 153, 255), null, null));
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        jPanel1.add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 190, 30));

        deletebtn.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        deletebtn.setText("DELETE");
        deletebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 153, 255), null, null));
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        jPanel1.add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 190, 30));

        label1.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(51, 51, 51));
        label1.setName("Returned Gallons"); // NOI18N
        label1.setText("Returned Gallons");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        gallonQuantity.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jPanel1.add(gallonQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 200, 40));

        customerName.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jPanel1.add(customerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 200, 40));

        gallonType1.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jPanel1.add(gallonType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DateReturnPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DateReturnPropertyChange
        //        setMinimumDate();
    }//GEN-LAST:event_DateReturnPropertyChange

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
//        try {
//            returngallonModel = new Return_GallonsModel(btn_id,customerControll.customerlist().get(Customer_Id.getSelectedIndex()).getID(),gallonControll.gallonList().get(gallonType_Id.getSelectedIndex()).getCode(),Integer.parseInt(gallonQuantity.getValue().toString()),df.format(DateReturn.getDate()));
//            if (borrowandreturngallonsControll.updateReturnGallon(returngallonModel,returngallonTable)) {
//                out.dispose();
//                new ContainerController(lalagyanan,new Views.PointOfSale.ReturnGallons(lalagyanan));
//
//            }
//        } catch (SQLException ex) {
//            java.util.logging.Logger.getLogger(ReturnGallonsFormModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed

        returngallonModel = new Return_GallonsModel(0,btn_id,Integer.parseInt(gallonQuantity.getText()),df.format(DateReturn.getDate()));
        if (addReturnGallon(returngallonModel,returngallons,borrowgallons)) {
            this.dispose();
            new ContainerController(lalagyanan,new Views.BorrowAndReturnGallons.BorrowAndReturnGallons(lalagyanan));
        }
        
    }//GEN-LAST:event_addbtnActionPerformed

    int minus;
    public boolean addReturnGallon(Return_GallonsModel returngallonModel,JTable returngallonTable,JTable borrowgallonTable){
        try {
            PreparedStatement st = con.prepareStatement("INSERT INTO `return_gallon`( `Borrowed_Gallons_Id`, `Gallon_Return_Quantity`, `Date_Return`) VALUES (?,?,?)");
            st.setInt(1, returngallonModel.getborrowedGallonsId());
            JOptionPane.showMessageDialog(null,borrowgallonquant);
            JOptionPane.showMessageDialog(null,returngallonModel.getGallon_Return_Quantity());
            if (returngallonModel.getGallon_Return_Quantity()>=borrowgallonquant) {
                JOptionPane.showMessageDialog(null,"0");
                minus = 0;
            }else if (returngallonModel.getGallon_Return_Quantity()<borrowgallonquant) {
                minus = borrowgallonquant - returngallonModel.getGallon_Return_Quantity();
                JOptionPane.showMessageDialog(null,minus);
            }
            st.setInt(2, returngallonModel.getGallon_Return_Quantity());
            st.setString(3, returngallonModel.getDate_Return());
            int i = st.executeUpdate();
            if (i > 0) {
                DefaultTableModel model = (DefaultTableModel)returngallonTable.getModel();
                DefaultTableModel models = (DefaultTableModel)borrowgallonTable.getModel();
                model.setRowCount(0);
                models.setRowCount(0);
                updateBorrow();
            } else {
                return false;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        return true;
     }
    
    public void updateBorrow(){
        try {
            PreparedStatement st = con.prepareStatement("UPDATE barrow_gallons SET Gallon_Quantity = ? , Status = ? WHERE ID = ?");
            st.setInt(1, minus);
            JOptionPane.showMessageDialog(null,minus);
            if (minus!=0) {
                st.setInt(2, 0);
            }else if (minus==0){
                st.setInt(2, 1);
            }
            st.setInt(3, returngallonModel.getborrowedGallonsId());
            int i = st.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(ReturnGallonsModal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
//        if(borrowandreturngallonsControll.deleteReturnGallons(btn_id,returngallonTable)){
//            out.dispose();
//            new ContainerController(lalagyanan,new Views.Gallons.Gallons(lalagyanan));
//        }
    }//GEN-LAST:event_deletebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnGallonsModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnGallonsModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnGallonsModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnGallonsModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnGallonsModal(btn_id,lalagyanan,returngallons,borrowgallons).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateReturn;
    public javax.swing.JButton addbtn;
    private javax.swing.JTextField customerName;
    public javax.swing.JButton deletebtn;
    private javax.swing.JTextField gallonQuantity;
    private javax.swing.JTextField gallonType1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    public javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
