/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Controllers.ContainerController;
import Controllers.SupplierController;
import Controllers.PromosController;
import static Forms.GallonsFormModal.gallonTable;
import static Forms.GallonsFormModal.lalagyanan;
import static Forms.GallonsFormModal.out;
import Models.GallonsModel;
import Models.SupplierModel;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author CALUAG FAMILY
 */
public class SuppliersFormModal extends javax.swing.JPanel {
    static int btn_id;
    SupplierController suliersControll = new SupplierController();  
    SupplierModel suppliermodel;
    static JTable suppliersTable;
    static JPanel lalagyanan;
    static JFrame out;
    /**
     * Creates new form SuppliersFormModal
     */
    public SuppliersFormModal(JFrame out,int btn_id,JTable suppliersTable,JPanel lalagyanan) {
        this.btn_id = btn_id;
        this.suppliersTable = suppliersTable;
        this.lalagyanan = lalagyanan;
        this.out = out;
        initComponents();
        checkBtn(btn_id);
    }
     private void checkBtn(int btn_id){
        if (btn_id==0) {
            updatebtn.setVisible(false);
            deletebtn.setVisible(false);
        }else{
           suliersControll.getSpplierInfo(btn_id, Fname,Mname, Lname, Company_name);
            addbtn.setVisible(false);
            updatebtn.setVisible(true);
            deletebtn.setVisible(true);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updatebtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Fname = new javax.swing.JTextField();
        Mname = new javax.swing.JTextField();
        Lname = new javax.swing.JTextField();
        Company_name = new javax.swing.JTextField();

        setBackground(new java.awt.Color(64, 43, 100));
        setPreferredSize(new java.awt.Dimension(310, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 100, 43));

        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 100, 43));

        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 100, 43));

        jLabel7.setText("First Name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, 30));

        jLabel8.setText("Last Name");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, 30));

        jLabel9.setText("Midle Name");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, 30));

        jLabel10.setText("Company Name");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 80, 30));

        Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameActionPerformed(evt);
            }
        });
        add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 180, 30));
        add(Mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 180, 30));
        add(Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 180, 30));
        add(Company_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
suppliermodel = new SupplierModel(btn_id,Fname.getText(),Lname.getText(),Mname.getText(),Company_name.getText());
        if (suliersControll.updateSupplier(suppliermodel,suppliersTable)) {
            out.dispose();
            new ContainerController(lalagyanan,new Views.Supplier(lalagyanan));
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
      suppliermodel = new SupplierModel(0,Fname.getText(),Lname.getText(),Mname.getText(),Company_name.getText());
        if (suliersControll.addSupplier(suppliermodel,suppliersTable)) {
            out.dispose();
            new ContainerController(lalagyanan,new Views.Supplier(lalagyanan));
        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        if(suliersControll.deleteSupplier(btn_id,suppliersTable)){
            out.dispose();
          new ContainerController(lalagyanan,new Views.Supplier(lalagyanan));
       }

    }//GEN-LAST:event_deletebtnActionPerformed

    private void FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Company_name;
    private javax.swing.JTextField Fname;
    private javax.swing.JTextField Lname;
    private javax.swing.JTextField Mname;
    public javax.swing.JButton addbtn;
    public javax.swing.JButton deletebtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
