/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Controllers.ContainerController;
import Controllers.SupplierController;
import Controllers.PromosController;
import static Forms.GallonsFormModal.gallonTable;
import static Forms.GallonsFormModal.lalagyanan;
import static Forms.GallonsFormModal.out;
import Models.GallonsModel;
import Models.SupplierModel;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author CALUAG FAMILY
 */
public class SuppliersFormModal extends javax.swing.JPanel {
    static int btn_id;
    SupplierController suliersControll = new SupplierController();  
    SupplierModel suppliermodel;
    static JTable suppliersTable;
    static JPanel lalagyanan;
    static JFrame out;
    /**
     * Creates new form SuppliersFormModal
     */
    public SuppliersFormModal(JFrame out,int btn_id,JTable suppliersTable,JPanel lalagyanan) {
        this.btn_id = btn_id;
        this.suppliersTable = suppliersTable;
        this.lalagyanan = lalagyanan;
        this.out = out;
        initComponents();
        checkBtn(btn_id);
    }
     private void checkBtn(int btn_id){
        if (btn_id==0) {
            updatebtn.setVisible(false);
            deletebtn.setVisible(false);
        }else{
           suliersControll.getSpplierInfo(btn_id, Fname,Mname, Lname, Company_name);
            addbtn.setVisible(false);
            updatebtn.setVisible(true);
            deletebtn.setVisible(true);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Fname = new javax.swing.JTextField();
        Mname = new javax.swing.JTextField();
        Lname = new javax.swing.JTextField();
        Company_name = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Company_Address = new javax.swing.JTextField();
        Contact = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(350, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Suppliers");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 22, 177, 37));

        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 546, 100, 43));

        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 100, 43));

        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 546, 100, 43));

        jLabel7.setText("First Name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, 30));

        jLabel8.setText("Last Name");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, 30));

        jLabel9.setText("Midle Name");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, 30));

        jLabel10.setText("Company Name");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 80, 30));

        Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameActionPerformed(evt);
            }
        });
        add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 220, 30));
        add(Mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 220, 30));
        add(Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 220, 30));
        add(Company_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 220, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("X");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 40, 30));

        jLabel11.setText("Company Address");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 90, 30));
        add(Company_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 220, 30));
        add(Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 220, 30));

        jLabel12.setText("Contact");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 90, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
suppliermodel = new SupplierModel(btn_id,Fname.getText(),Lname.getText(),Mname.getText(),Company_name.getText(),Company_Address.getText(),Contact.getName());
        if (suliersControll.updateSupplier(suppliermodel,suppliersTable)) {
            out.dispose();
            new ContainerController(lalagyanan,new Views.Supplier(lalagyanan));
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
      suppliermodel = new SupplierModel(0,Fname.getText(),Lname.getText(),Mname.getText(),Company_name.getText(),Company_Address.getText(),Contact.getName());
        if (suliersControll.addSupplier(suppliermodel,suppliersTable)) {
            out.dispose();
            new ContainerController(lalagyanan,new Views.Supplier(lalagyanan));
        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        if(suliersControll.deleteSupplier(btn_id,suppliersTable)){
            out.dispose();
          new ContainerController(lalagyanan,new Views.Supplier(lalagyanan));
       }

    }//GEN-LAST:event_deletebtnActionPerformed

    private void FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        out.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Company_Address;
    private javax.swing.JTextField Company_name;
    private javax.swing.JTextField Contact;
    private javax.swing.JTextField Fname;
    private javax.swing.JTextField Lname;
    private javax.swing.JTextField Mname;
    public javax.swing.JButton addbtn;
    public javax.swing.JButton deletebtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
