/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Controllers.ContainerController;
import static Forms.FrameFormModal.btn_id;
import static Forms.FrameFormModal.containernum;
import static Forms.FrameFormModal.jtablename;
import static Forms.FrameFormModal.lalagyanan;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author CALUAG FAMILY
 */
public class UserFrameModal extends javax.swing.JFrame {

    /**
     * Creates new form UserFrameModal
     */
    
    static int containernum;
    static int btn_id;
    static JTable jtablename;
    static JPanel lalagyanan;
    static JFrame maindash;
    
    public UserFrameModal(int containernum,int btn_id,JTable jtablename,JPanel lalagyanan,JFrame maindash) {
        initComponents();
        this.containernum = containernum;
        this.btn_id = btn_id;
        this.jtablename = jtablename;
        this.lalagyanan = lalagyanan;
        this.maindash = maindash;
        new ContainerController(formContainer,new UserFormModal(this,btn_id,jtablename,lalagyanan,maindash));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formContainer.setPreferredSize(new java.awt.Dimension(350, 600));
        formContainer.setLayout(new javax.swing.BoxLayout(formContainer, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(formContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrameModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrameModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrameModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrameModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFrameModal(containernum,btn_id,jtablename,lalagyanan,maindash).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel formContainer;
    // End of variables declaration//GEN-END:variables
}
